#!/usr/bin/env python

Import("env")
Import("env_modules")

env_rnnoise = env_modules.Clone()

module_obj = []

env_rnnoise.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

env_rnnoise.Append(CPPPATH=["thirdparty"])

env.Append(LIBPATH=["../../modules/rnnoise/thirdparty/build"])
env.Append(LIBS=["rnnoise"])
